# Generated by Django 2.2.5 on 2020-06-11 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nv_code', models.CharField(blank=True, max_length=50)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('kr_name', models.CharField(blank=True, max_length=50)),
                ('en_name', models.CharField(blank=True, max_length=50)),
                ('en_search', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('naver', models.IntegerField()),
                ('rotten', models.IntegerField()),
                ('imbd', models.IntegerField()),
                ('users', models.ManyToManyField(blank=True, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
