# Generated by Django 2.2.5 on 2020-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nv_code', models.CharField(blank=True, max_length=50)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('kr_name', models.CharField(blank=True, max_length=50)),
                ('en_name', models.CharField(blank=True, max_length=50)),
                ('en_search', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('naver', models.IntegerField()),
                ('naver_link', models.CharField(blank=True, max_length=50)),
                ('rotten', models.IntegerField()),
                ('rotten_link', models.CharField(blank=True, max_length=50)),
                ('imdb', models.IntegerField()),
                ('imdb_link', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
