# Generated by Django 2.2.5 on 2020-06-25 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
