# Generated by Django 2.2.5 on 2020-06-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='naver',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rotten',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
